###
GET http://localhost:3001/

####
get http://localhost:3001/users

###
post http://localhost:3001/login
Content-Type: application/json

{
    "username" : "keaziah",
    "password": "mati123"
}

###
post http://localhost:3001/register
Content-Type: application/json

{
    "username": "keaziah",
    "fullname": "Keziah Mati",
    "email": "mati@gmail.com",
    "password": "mati123",
    "cpassword": "mati123"
}