###
GET http://localhost:3001/

####
get http://localhost:3001/users

###
post http://localhost:3001/login
Content-Type: application/json

{
    "username" : "Randomhunter47",
    "password": "eugene123"
}