export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_FAIL = "SIGNUP_FAIL"
export const SIGNUP_STATUS = "SIGNUP_STATUS"

export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGIN_REQUEST = "LOGIN_REQUEST"

export const LOG_OUT = "LOG_OUT"

export const GET_USERS_REQUEST = "GET_USERS_REQUEST"
export const GET_USERS_FAILED = "GET_USERS_FAILED"
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"