export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_FAIL = "SIGNUP_FAIL"
export const SIGNUP_STATUS = "SIGNUP_STATUS"

export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGIN_REQUEST = "LOGIN_REQUEST"

export const LOG_OUT = "LOG_OUT"

export const GET_USERS_REQUEST = "GET_USERS_REQUEST"
export const GET_USERS_FAILED = "GET_USERS_FAILED"
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"

export const GET_PROJECTS_REQUEST = "GET_PROJECTS_REQUEST"
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS"
export const GET_PROJECTS_FAILED = "GET_PROJECTS_FAILED"

export const GET_TASKS_REQUEST = "GET_TASKS_REQUEST"
export const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS"
export const GET_TASKS_FAILED = "GET_TASKS_FAILED"

export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS"
export const CREATE_TASK_FAILED = "CREATE_TASK_FAILED"

export const ASSIGN_TASK_SUCCESS = "ASSIGN_TASK_SUCCESS"
export const ASSIGN_TASK_FAILED = "ASSIGN_TASK_FAILED"